# Generated by Django 4.1.7 on 2023-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_chat_notification_tags_alumni_company_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_contact',
            field=models.IntegerField(default=None, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Alumni'), ('C', 'Company'), ('F', 'Admin')], default='F', max_length=1, verbose_name='Role'),
        ),
    ]
