# Generated by Django 4.1.7 on 2023-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_user_contact_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_contact',
            field=models.IntegerField(default='0', verbose_name='Contact'),
        ),
    ]
