# Generated by Django 4.1.7 on 2023-04-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_tags_delete_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('mail_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterField(
            model_name='alumni',
            name='graduating_year',
            field=models.IntegerField(verbose_name='Graduating Year'),
        ),
    ]
