# Generated by Django 4.2 on 2023-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact_alter_alumni_graduating_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'mails'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail_content',
            field=models.TextField(verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender_mail',
            field=models.EmailField(max_length=254, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='contact',
            table='mail',
        ),
    ]
