# Generated by Django 4.2 on 2023-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_options_alter_contact_mail_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mail_content',
            field=models.TextField(default='', verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender_mail',
            field=models.EmailField(default='', max_length=254, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=9, unique=True, verbose_name='Roll Number'),
        ),
    ]
